---
name: libblkid cargo CI

# yamllint disable-line rule:truthy
on:
  push:
    branches: [master]
    paths:
      - '**/Cargo.toml'
      - '.github/workflows/cargo.yml'
  pull_request:
    branches: [master]
    paths:
      - '**/Cargo.toml'
      - '.github/workflows/cargo.yml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  checks-with-ci-repo:
    runs-on: ubuntu-20.04
    container:
      image: fedora:39  # CURRENT DEVELOPMENT ENVIRONMENT
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies for Fedora
        run: >
          dnf install -y
          clang
          curl
          git
          libblkid-devel
          make
          openssl-devel
          python-requests
          python-semantic_version
      - uses: dtolnay/rust-toolchain@master
        with:
          components: cargo
          toolchain: 1.76.0  # CURRENT DEVELOPMENT RUST TOOLCHAIN
      - name: Check out ci repo
        run: git clone https://github.com/stratis-storage/ci.git
      - name: Run comparisons of version specs with available Fedora packages
        # yamllint disable rule:line-length
        run: |
          # -sys
          COMPARE_FEDORA_VERSIONS=./compare_fedora_versions MANIFEST_PATH=../../libblkid-rs-sys/Cargo.toml FEDORA_RELEASE=rawhide IGNORE_ARGS="--ignore-category low" make -f ../../Makefile check-fedora-versions
          COMPARE_FEDORA_VERSIONS=./compare_fedora_versions MANIFEST_PATH=../../libblkid-rs-sys/Cargo.toml FEDORA_RELEASE=f39 IGNORE_ARGS="--ignore-category low" make -f ../../Makefile check-fedora-versions
          COMPARE_FEDORA_VERSIONS=./compare_fedora_versions MANIFEST_PATH=../../libblkid-rs-sys/Cargo.toml FEDORA_RELEASE=f38 IGNORE_ARGS="--ignore-category low" make -f ../../Makefile check-fedora-versions
          # main
          COMPARE_FEDORA_VERSIONS=./compare_fedora_versions MANIFEST_PATH=../../Cargo.toml FEDORA_RELEASE=rawhide IGNORE_ARGS="--ignore-category low --ignore-high=libblkid-rs-sys" make -f ../../Makefile check-fedora-versions
          COMPARE_FEDORA_VERSIONS=./compare_fedora_versions MANIFEST_PATH=../../Cargo.toml FEDORA_RELEASE=f39 IGNORE_ARGS="--ignore-category low --ignore-high=libblkid-rs-sys" make -f ../../Makefile check-fedora-versions
          COMPARE_FEDORA_VERSIONS=./compare_fedora_versions MANIFEST_PATH=../../Cargo.toml FEDORA_RELEASE=f38 IGNORE_ARGS="--ignore-category low --ignore-high=libblkid-rs-sys" make -f ../../Makefile check-fedora-versions
        working-directory: ./ci/dependency_management
